server:
  port: 10701

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

spring:
  application:
    name: third-part-service

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'